name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.MINECRAFT_HOST }}
          username: ${{ secrets.MINECRAFT_USER }}
          key: ${{ secrets.MINECRAFT_KEY }}
          port: ${{ secrets.MINECRAFT_PORT }}
          uploads: |
            ./ => ${{ secrets.MINECRAFT_TARGET_DIR }}
          ignore: |
            .git/
            .github/
            .gitignore

      - name: Compile Spigot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINECRAFT_HOST }}
          username: ${{ secrets.MINECRAFT_USER }}
          key: ${{ secrets.MINECRAFT_KEY }}
          script: |
            cd ${{ secrets.MINECRAFT_TARGET_DIR }}/buildtools
            bash setup_spigot.sh
